### ISSUE TITLE
Code structure: what does cleanr stand for?

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/blog-extension#6]
https://github.com/canonical-webteam/blog-flask-extension/pull/1#discussion_r256790950

https://github.com/tbille/blog-flask-extension/blob/187c88dd0959301eaad3eb67f2b333dddd2f0635/canonicalwebteam/blog_extension/logic.py#L14

**Comment by nottrobin** [comment]
https://github.com/tbille/blog-flask-extension/blob/187c88dd0959301eaad3eb67f2b333dddd2f0635/canonicalwebteam/blog_extension/logic.py#L14

**Comment by tbille** [comment]
Fixed in the PR
