### ISSUE TITLE
Code structure: Do we need to escape backslashes?

### ISSUE THREAD

**Issue by nottrobin** [canonical-webteam/blog-extension#7]
As mentioned here: https://github.com/canonical-webteam/blog-flask-extension/pull/1#pullrequestreview-203705694

https://github.com/tbille/blog-flask-extension/blob/187c88dd0959301eaad3eb67f2b333dddd2f0635/canonicalwebteam/blog_extension/logic.py#L111

**Comment by tbille** [comment]
Fixed

**Comment by nottrobin** [comment]
@tbille where?

**Comment by nottrobin** [comment]
Ah, I see it was fixed [in the PR itself](https://github.com/canonical-webteam/blog-extension/pull/1/files#diff-9e910b030c25044a53542ef84c7174ccR111), as with #6.
